repos:
- repo: local
  hooks:
  - id: clang-format
    name: clang-format
    entry: clang-format
    args: ["-style=file", "-i"]
    language: system
    files: \.[ch](pp)?$
  - id: imports
    name: imports
    entry: tools/sort_imports
    language: system
    files: \.[ch](pp)?$
