name: Publish a new release

permissions:
  contents: write

on:
  push:
    branch: stable
    tags:
      - 'v?[0-9]*'
  workflow_call:
    inputs:
      release_name:
        description: 'Release name'
        required: true
        default: 'Release ${{ github.ref_name }}'
        type: string
      tag_name:
        description: 'Tag name'
        required: false
        default: '${{ github.ref }}'
        type: string
      draft:
        description: 'Draft'
        required: true
        default: false
        type: boolean
      prerelease:
        description: 'Prerelease'
        required: true
        type: boolean

jobs:
  publish_release:
    name: 'Create a GitHub release'
    runs-on: ubuntu-latest
    needs:
      - package_game_win
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v3
        with:
          path: .
          fetch-tags: true

      - name: 'Download built assets'
        uses: actions/download-artifact@v1
        with:
          name: game_win_zip
          path: artifacts/

      - name: 'Prepare the changelog'
        id: prepare_changelog
        uses: ./.github/actions/prepare_changelog

      - name: 'Get version'
        id: get_version
        uses: ./.github/actions/get_version

      - name: 'Prepare for the release'
        run: |
          echo "${{steps.prepare_changelog.outputs.changelog }}" >artifacts/changes.txt
          mv artifacts/game-win.zip artifacts/TR2X-${{ steps.get_version.outputs.version }}-Windows.zip

      - name: 'Delete old release assets'
        uses: mknejp/delete-release-assets@v1
        continue-on-error: true
        with:
          token: ${{ github.token }}
          tag: ${{ inputs.tag_name }}
          assets: '*.*'

      - name: 'Publish the release'
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ inputs.release_name }}
          body_path: artifacts/changes.txt
          draft: ${{ inputs.draft }}
          prerelease: ${{ inputs.prerelease }}
          fail_on_unmatched_files: true
          tag_name: ${{ inputs.tag_name }}
          files: |
            artifacts/TR2X-${{ steps.get_version.outputs.VERSION }}-Windows.zip

  package_game_win:
    name: 'Package the game (Windows)'
    uses: ./.github/workflows/build_game_win.yml
